"""app_config kv table for behavior tuning

Revision ID: cefad7f08cb2
Revises: d4f171ae7ba7
Create Date: 2026-06-01 13:43:32.813048

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cefad7f08cb2"
down_revision: str | None = "d4f171ae7ba7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at_db",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.alter_column(
        "cameras",
        "risk_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cameras",
        "risk_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'70'::double precision"),
        existing_nullable=False,
    )
    op.drop_table("app_config")
    # ### end Alembic commands ###
